### ISSUE TITLE
Course locations do not load

### ISSUE THREAD

**Issue by jerryand100** [course-planner/course-planner#10]
Summary: When viewing the section offering information of a course, the course location is blank.

Description: Every row of the 'class=sectionDetailList' table on the page throws the following error:

         Error in event handler for (unknown): TypeError: link.append is not a function
              at chrome-extension://lbkhimhcjfpecmjlbplpkgfjjhbmajge/js/course_page.js:197:24

Severity: High

Example: Noticed when viewing the section information for CS 200 for Fall 2017-2018

Suggestions: I believe link.appendChild() may be the function you need instead of link.append().

**Comment by JDKardia** [comment]
Can you tell us what browser you're using and whether you're using an ad blocker of some sort? We think that may be the issue at hand.

**Comment by jerryand100** [comment]
I am using Chrome version 53.0.2785.116 (64-bit) on Ubuntu.
I disabled my ad blocker, re-ran the extension, and the issue still persists.

If it's of any help, I also ran it in the beta version of a browser called Yandex and letter-for-letter got the same error message as in Chrome.

**Comment by JDKardia** [comment]
Got it, good to know. We'll look into the issue!

**Comment by GraysonFreking** [comment]
Any chance you could include a screenshot of what you are seeing in the webpage screen during this error?

**Comment by jerryand100** [comment]
![_005](https://cloud.githubusercontent.com/assets/11963884/25415645/9772c0f6-29fe-11e7-83ae-9689bf156737.png)

**Comment by jerryand100** [comment]
Everything else loads fine, it just looks like the function responsible for turning the textual location into a link errors out, and thus the locations aren't printed.

**Comment by GraysonFreking** [comment]
Since I am unable to replicate the bug from my end, not matter what I do, I have tried changing link.append to link.appendChild per your suggestion.

Will you please let us know if this worked through your browser?

**Comment by jerryand100** [comment]
![_006](https://cloud.githubusercontent.com/assets/11963884/25458381/48b97cec-2a9f-11e7-84dd-030bca26a19c.png)

That fixed it on my end. You can see the code change on line 197 from the screenshot above, and sure enough, all the course links show up as anticipated.

**Comment by GraysonFreking** [comment]
thanks!
