### ISSUE TITLE
RMP display suggestion

### ISSUE THREAD

**Issue by wjwdehao** [course-planner/course-planner#17]
Summary: suggestions on ratemyprofessor information displaying. 
Description: for example, 
![suggestiononrmp](https://cloud.githubusercontent.com/assets/20054538/25546301/0efb504a-2c28-11e7-9eb6-1a1ee6f4e645.png)

Professor Zev got an extremely high rating on RMP, however, almost every friend of mine who is taking CS 537 this semester suffered a lot in his class, thinks his way of teaching is not appropriate or exam is too difficult. 
I went to the link on RMP: 
![suggestiononrmp2](https://cloud.githubusercontent.com/assets/20054538/25546480/e51f5b62-2c28-11e7-8f94-67fb6be22859.png)

The reason why the rating is so high is that only one student gives rating, which may introduce some bias. 
I know that is not your responsibility but I think if we can display number of students who rated on RMP, that would help students better understand the rating. 

Severity: trivial
Suggestion: display the number of students who have rated on RMP on that professor when mouse hovers over it.

**Comment by Normanlinsh** [comment]
Added number of ratings info for RMP hover over
