### ISSUE TITLE
100% grade-distribution vertical-axis scaling

### ISSUE THREAD

**Issue by jerryand100** [course-planner/course-planner#19]
Summary: vertical-axis scaling is quirky when one grade has 100% of the values.

Description: When 100% of students get the same grade, the vertical axis scales to 120%, making it look like only 80% of students got the grade.

![_007](https://cloud.githubusercontent.com/assets/11963884/25550540/9238ec4e-2c3f-11e7-80df-26167dcf6ea1.png)

Severity: Trivial

Suggestion: Make an exception at 100% for rescaling the vertical axis.

**Comment by zjpetersen** [comment]
This issue got fixed when we moved to the ChartJS library.  For some reason you were using an outdated version of the extension.
