### ISSUE TITLE
RMP and grades dropdown only work after ave. GPA filled in

### ISSUE THREAD

**Issue by zjpetersen** [course-planner/course-planner#3]
To reproduce this issue:
Login to course guide spring term.
Search by computer science
Scroll down to Algorithms 577, try to click the grades dropdown or hover over the RMP score.  Neither will work.
Watch as the ave grades get filled in.
Once they fill into the bottom the grades dropdown works and you can see the professors score.

**Comment by bowernite** [comment]
Currently seems to be working fine since the courses' average GPAs were added to the back end, but not sure what else we can do about this if the database acts up again.
