### ISSUE TITLE
Professors who exist in RateMyProfessor are not found by the extension

### ISSUE THREAD

**Issue by jerryand100** [course-planner/course-planner#9]
Summary: Some professors who have a RMP page are not found by the extension.

Description: Some professors, namely those whose names are different on their RMP page, are reported not found by the extension.

Severity: Medium

Example: For CS 252 Spring 2016/2017 LEC 002, the listed professor is "Nayar, Radhakrishnan Rahul", and he is reported not found. Searching for Rahul Nayar finds a page associated with the correct teacher.

Suggestions: Try leaving out 'extra' (ie not first or last names) in searches.

**Comment by Normanlinsh** [comment]
Added additional checks for professor names
